export default [
  "M.O Efetiva",
  "M.O Eventual",
  "Concentrados",
  "Núcleos/Minerais/Aditivos",
  "Volumosos",
  "DietaCria/Recria",
  "Energia/Comunicação",
  "Diesal/Combustível",
  "Manutenção/Máquinas/Equipamentos",
  "Produtos Ordenha",
  "Produtos Veterinários",
  "BST",
  "Sêmen",
  "Despesas Tecnicas",
  "Despesas Investimentos",
  "Outras despesas",
  "Pró-Labore",
];
